ServerEvents.recipes(e => {
    e.remove({ id: "bloodmagic:altar/weakbloodorb" })
    e.recipes.bloodmagic.altar('bloodmagic:weakbloodorb', 'eidolon:unholy_symbol')
        .upgradeLevel(0)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(1)
        .id('kubejs:altar/weakbloodorb')

    e.remove({ id: "bloodmagic:altar/apprenticebloodorb" })
    e.recipes.bloodmagic.altar('bloodmagic:apprenticebloodorb', 'meetyourfight:caged_heart')
        .upgradeLevel(1)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:altar/apprenticebloodorb')

    e.remove({ id: "bloodmagic:altar/magicianbloodorb" })
    e.recipes.bloodmagic.altar('bloodmagic:magicianbloodorb', 'botania:mana_tablet')
        .upgradeLevel(2)
        .altarSyphon(50000)
        .consumptionRate(20)
        .drainRate(20)
        .id('kubejs:altar/magicianbloodorb')

    e.remove({ id: "bloodmagic:altar/slate" })
    e.recipes.bloodmagic.altar('bloodmagic:blankslate', 'occultism:otherstone_tablet')
        .upgradeLevel(0)
        .altarSyphon(1000)
        .consumptionRate(50)
        .drainRate(5)
        .id('kubejs:altar/slate')

    e.remove({ id: "bloodmagic:altar/reinforcedslate" })
    e.recipes.bloodmagic.altar('bloodmagic:reinforcedslate', 'bloodmagic:blankslate')
        .upgradeLevel(1)
        .altarSyphon(2000)
        .consumptionRate(100)
        .drainRate(5)
        .id('kubejs:altar/reinforcedslate')

    e.remove({ id: "bloodmagic:altar/imbuedslate" })
    e.recipes.bloodmagic.altar('bloodmagic:infusedslate', 'bloodmagic:reinforcedslate')
        .upgradeLevel(2)
        .altarSyphon(5000)
        .consumptionRate(250)
        .drainRate(10)
        .id('kubejs:altar/imbuedslate')

    e.remove({ id: "bloodmagic:altar/demonicslate" })
    e.recipes.bloodmagic.altar('bloodmagic:demonslate', 'bloodmagic:infusedslate')
        .upgradeLevel(3)
        .altarSyphon(15000)
        .consumptionRate(750)
        .drainRate(20)
        .id('kubejs:altar/demonicslate')

    e.recipes.bloodmagic.altar('bloodmagic:etherealslate', 'bloodmagic:demonslate')
        .upgradeLevel(4)
        .altarSyphon(200000)
        .consumptionRate(1000)
        .drainRate(1000)
        .id('kubejs:bloodaltar/etherealslate')

    e.remove({ id: "occultism:spirit_fire/chalk_white" })
    e.recipes.bloodmagic.altar('occultism:chalk_white', 'occultism:chalk_white_impure')
        .upgradeLevel(0)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(1)
        .id('kubejs:spirit_fire/chalk_white')

    e.remove({ id: "occultism:spirit_fire/chalk_gold" })
    e.recipes.bloodmagic.altar('occultism:chalk_gold', 'occultism:chalk_gold_impure')
        .upgradeLevel(1)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:spirit_fire/chalk_gold')

    e.remove({ id: "occultism:spirit_fire/chalk_purple" })
    e.recipes.bloodmagic.altar('occultism:chalk_purple', 'occultism:chalk_purple_impure')
        .upgradeLevel(2)
        .altarSyphon(25000)
        .consumptionRate(20)
        .drainRate(20)
        .id('kubejs:spirit_fire/chalk_purple')

    e.remove({ id: "occultism:spirit_fire/chalk_red" })
    e.recipes.bloodmagic.altar('occultism:chalk_red', 'occultism:chalk_red_impure')
        .upgradeLevel(3)
        .altarSyphon(40000)
        .consumptionRate(30)
        .drainRate(50)
        .id('kubejs:spirit_fire/chalk_red')

    e.remove({ id: "bloodmagic:altar/soul_snare" })
    e.recipes.bloodmagic.altar('bloodmagic:soulsnare', 'ars_nouveau:magebloom_fiber')
        .upgradeLevel(1)
        .altarSyphon(500)
        .consumptionRate(5)
        .drainRate(1)
        .id('kubejs:altar/soul_snare')

    e.recipes.bloodmagic.altar('architects_palette:moonstone', 'kubejs:firmament')
        .upgradeLevel(0)
        .altarSyphon(5000)
        .consumptionRate(250)
        .drainRate(1)
        .id('kubejs:bloodaltar/moonstone')

    e.remove({ id: "bloodmagic:sacrificial_dagger" })
    e.recipes.bloodmagic.altar('bloodmagic:sacrificialdagger', Item.of('eidolon:sapping_sword', '{Damage:0}').weakNBT())
        .upgradeLevel(1)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:sacrificial_dagger')

    e.remove({ id: "bloodmagic:altar/masterbloodorb" })
    e.recipes.bloodmagic.altar('bloodmagic:masterbloodorb', 'create:shadow_steel')
        .upgradeLevel(3)
        .altarSyphon(80000)
        .consumptionRate(30)
        .drainRate(50)
        .id('kubejs:altar/masterbloodorb')

    e.remove({ id: "bloodmagic:altar/air_tool" })
    e.recipes.bloodmagic.altar('bloodmagic:airscribetool', '#botania:runes/air')
        .upgradeLevel(2)
        .altarSyphon(1000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:altar/air_tool')

    e.remove({ id: "bloodmagic:altar/fire_tool" })
    e.recipes.bloodmagic.altar('bloodmagic:firescribetool', '#botania:runes/fire')
        .upgradeLevel(2)
        .altarSyphon(1000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:altar/fire_tool')

    e.remove({ id: "bloodmagic:altar/water_tool" })
    e.recipes.bloodmagic.altar('bloodmagic:waterscribetool', '#botania:runes/water')
        .upgradeLevel(2)
        .altarSyphon(1000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:altar/water_tool')

    e.remove({ id: "bloodmagic:altar/earth_tool" })
    e.recipes.bloodmagic.altar('bloodmagic:earthscribetool', '#botania:runes/earth')
        .upgradeLevel(2)
        .altarSyphon(1000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:altar/earth_tool')

    e.remove({ id: "bloodmagic:altar/dusk_tool" })
    e.recipes.bloodmagic.altar('bloodmagic:duskscribetool', '#botania:runes/nidavellir')
        .upgradeLevel(3)
        .altarSyphon(2000)
        .consumptionRate(20)
        .drainRate(10)
        .id('kubejs:altar/dusk_tool')

    e.recipes.bloodmagic.altar('eidolon:polished_planks', 'botania:livingwood_planks')
        .upgradeLevel(0)
        .altarSyphon(50)
        .consumptionRate(25)
        .drainRate(5)
        .id('kubejs:bloodaltar/polished_planks')

    e.remove({ id: "waystones:warp_stone" })
    e.recipes.bloodmagic.altar('waystones:warp_stone', 'ars_nouveau:ritual_warping')
        .upgradeLevel(2)
        .altarSyphon(25000)
        .consumptionRate(20)
        .drainRate(20)
        .id('kubejs:warp_stone')

    e.recipes.bloodmagic.altar('botania:fel_pumpkin', 'undergarden:gloom_o_lantern')
        .upgradeLevel(0)
        .altarSyphon(1000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:bloodaltar/fel_pumpkin')

    e.recipes.bloodmagic.altar('botania:blood_pendant', 'eidolon:void_amulet')
        .upgradeLevel(1)
        .altarSyphon(7000)
        .consumptionRate(5)
        .drainRate(5)
        .id('kubejs:bloodaltar/blood_pendant')
})