//priority: 1000

const bookshelves = [
    'atmospheric:aspen_bookshelf',
    'atmospheric:grimwood_bookshelf',
    'atmospheric:kousa_bookshelf',
    'atmospheric:morado_bookshelf',
    'atmospheric:rosewood_bookshelf',
    'atmospheric:yucca_bookshelf',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    'environmental:cherry_bookshelf',
    'environmental:willow_bookshelf',
    'environmental:wisteria_bookshelf',
    'minecraft:bookshelf',
    'quark:acacia_bookshelf',
    'quark:birch_bookshelf',
    'quark:crimson_bookshelf',
    'quark:dark_oak_bookshelf',
    'quark:jungle_bookshelf',
    'quark:spruce_bookshelf',
    'quark:warped_bookshelf',
    'upgrade_aquatic:driftwood_bookshelf',
    'upgrade_aquatic:river_bookshelf'
];
