//priority: 1000

// Items added here will get recipes for Pedestals & Cobblegen Randomizer cobblegens.
const generatableCobblestone = [
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    'create:andesite_cobblestone',
    'create:diorite_cobblestone',
    'create:granite_cobblestone',
    'quark:cobbedstone',
    'quark:cobbled_deepslate',
    'create:dark_scoria_cobblestone',
    'create:scoria_cobblestone',
    'create:gabbro_cobblestone',
    'create:dolomite_cobblestone',
    'create:weathered_limestone_cobblestone',
    'create:limestone_cobblestone',
    'atmospheric:saffron_travertine',
    'atmospheric:persimmon_travertine',
    'atmospheric:peach_travertine',
    'atmospheric:ivory_travertine',
    /*'atum:'*/ 'kubejs:replaceme'
];
// Items added here will get recipes for Pedestals & Cobblegen Randomizer stonegens.
const generatableStone = [
    'minecraft:andesite',
    'minecraft:diorite',
    'minecraft:granite',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    /*'byg:'*/ 'kubejs:replaceme',
    'minecraft:red_sandstone',
    'minecraft:sandstone',
    'quark:basalt',
    'quark:brimstone',
    'quark:jasper',
    'quark:limestone',
    'quark:marble',
    'quark:permafrost',
    'quark:slate',
    'quark:deepslate',
    /*'astralsorcery:'*/ 'kubejs:replaceme',
    'create:dark_scoria',
    'create:scoria',
    'create:natural_scoria',
    'create:gabbro',
    'create:dolomite',
    'create:weathered_limestone',
    'create:limestone',
    'atmospheric:red_arid_sandstone',
    'atmospheric:arid_sandstone',
    /*'atum:'*/ 'kubejs:replaceme',
    /*'atum:'*/ 'kubejs:replaceme',
    'quark:myalite',
    'quark:dusky_myalite',
    'undergarden:shiverstone',
    'undergarden:depthrock',
    'undergarden:tremblecrust'
];
const generatableBasalt = [];
