//priority: 1000
const fishableFish = [
    'alexsmobs:blobfish',
    'aquaculture:arapaima',
    'aquaculture:atlantic_cod',
    'aquaculture:atlantic_halibut',
    'aquaculture:atlantic_herring',
    'aquaculture:bayad',
    'aquaculture:blackfish',
    'aquaculture:bluegill',
    'aquaculture:boulti',
    'aquaculture:brown_shrooma',
    'aquaculture:brown_trout',
    'aquaculture:capitaine',
    'aquaculture:carp',
    'aquaculture:catfish',
    'aquaculture:gar',
    'aquaculture:goldfish',
    'aquaculture:minnow',
    'aquaculture:muskellunge',
    'aquaculture:pacific_halibut',
    'aquaculture:perch',
    'aquaculture:pink_salmon',
    'aquaculture:piranha',
    'aquaculture:pollock',
    'aquaculture:rainbow_trout',
    'aquaculture:red_grouper',
    'aquaculture:red_shrooma',
    'aquaculture:smallmouth_bass',
    'aquaculture:synodontis',
    'aquaculture:tambaqui',
    'aquaculture:tuna',
    /*'atum:'*/ 'kubejs:replaceme',
    /*'atum:'*/ 'kubejs:replaceme',
    /*'atum:'*/ 'kubejs:replaceme',
    /*'atum:'*/ 'kubejs:replaceme',
    /*'betterendforge:'*/ 'kubejs:replaceme',
    'environmental:koi',
    'minecraft:cod',
    'minecraft:pufferfish',
    'minecraft:salmon',
    'minecraft:tropical_fish',
    'sushigocrafting:raw_tuna',
    'undergarden:raw_gwibling',
    'upgrade_aquatic:lionfish',
    'upgrade_aquatic:perch',
    'upgrade_aquatic:pike'
];
