ServerEvents.recipes(e => {
    e.replaceOutput({}, 'thermal:cinnabar', '#forge:gems/cinnabar')
    e.replaceOutput({}, 'thermal:sulfur', '#forge:gems/sulfur')
    e.replaceOutput({}, 'thermal:apatite', '#forge:gems/apatite')
    e.replaceOutput({}, 'thermal:niter', '#forge:gems/niter')
    e.replaceOutput({}, 'thermal:bitumen', '#forge:gems/bitumen')
    e.replaceOutput({}, 'thermal:coal_coke', '#forge:gems/coal_coke')
    e.replaceOutput({}, 'thermal:rubber', 'industrialforegoing:dryrubber')
    e.replaceOutput({}, 'immersiveengineering:slag', 'thermal:slag')
    e.replaceOutput({}, 'create:dough', 'farmersdelight:wheat_dough')
    e.replaceOutput({}, 'simplefarming:chocolate', 'create:bar_of_chocolate')
    e.replaceOutput({}, 'minecraft:iron_ingot', 'dustrial_decor:rusty_iron_ingot')
    e.replaceOutput({}, 'minecraft:iron_nugget', 'dustrial_decor:rusty_iron_nugget')
})