/* 
    obj[0] = gets the name of material object
    obj[1] = gets the material object, letting you access the data like .type
    addFlags = adds these flags to the item, e.g. ['crystal', 'clump', 'ingot']
    delFlags = remove these flags from the items types base flags, e.g. ['crystal', 'clump', 'ingot']
 */
global.emendatus_mats = {
    // - - vanilla - - 
    coal: { type: 'vanilla', toolLvl: 'wood', isVanilla: true, addFlags: [], delFlags: [] },
    copper: { type: 'vanilla', toolLvl: 'stone', isVanilla: true, addFlags: [], delFlags: ['cluster_shard'] },
    diamond: { type: 'vanilla', toolLvl: 'iron', isVanilla: true, addFlags: [], delFlags: [] },
    emerald: { type: 'vanilla', toolLvl: 'iron', isVanilla: true, addFlags: [], delFlags: [] },
    gold: { type: 'vanilla', toolLvl: 'iron', isVanilla: true, addFlags: [], delFlags: ['cluster_shard'] },
    iron: { type: 'vanilla', toolLvl: 'stone', isVanilla: true, addFlags: [], delFlags: ['cluster_shard'] },
    lapis: { type: 'vanilla', toolLvl: 'stone', isVanilla: true, addFlags: [], delFlags: [] },
    netherite: { type: 'vanilla', toolLvl: 'diamond', isVanilla: true, addFlags: [], delFlags: ['clump', 'dirty_dust', 'crystal', 'shard', 'crushed_ore', 'cluster_shard', 'ore'] },
    quartz: { type: 'vanilla', toolLvl: 'stone', isVanilla: true, addFlags: [], delFlags: [] },
    redstone: { type: 'vanilla', toolLvl: 'iron', isVanilla: true, addFlags: [], delFlags: ['dust'] },
    // - - alloy - - 
    brass: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    bronze: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    constantan: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    electrum: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    enderium: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    graphite: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    invar: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    lumium: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    signalum: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    steel: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    fiery: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    infused_iron: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    ironwood: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    knightmetal: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    orichalcum: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    refined_glowstone: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    refined_obsidian: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    rose_gold: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    sky: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    soul_steel: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    tainted_gold: { type: 'alloy', toolLvl: 'stone', addFlags: [], delFlags: [] },
    // - - gem - - 
    apatite: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    bitumen: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    charoite: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    cinnabar: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    dimensional: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    diopside: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    moonstone: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    potassium_nitrate: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    pyrope: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    sapphire: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    sulfur: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    aquite: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    arcane: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    carminite: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: ['dirty_dust'] },
    certus_quartz: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    // charged_certus_quartz: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    fluorite: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    peridot: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    ruby: { type: 'gem', toolLvl: 'stone', addFlags: [], delFlags: [] },
    // - - metal - -
    aluminum: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['crushed_ore'] },
    iridium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['crushed_ore'] },
    lead: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['shard', 'crushed_ore'] },
    nickel: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    platinum: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    silver: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    tin: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['shard'] },
    titanium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    tungsten: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    uranium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['shard'] },
    zinc: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['crushed_ore'] },
    cobalt: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['crushed_ore'] },
    falsite: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    horizonite: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    osmium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: ['shard'] },
    ventium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] },
    iesnium: { type: 'metal', toolLvl: 'stone', addFlags: [], delFlags: [] }
    // - - no default flags - -
}