
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "emendatus", "kubejs", "thermal", "tconstruct", "tcintegrations", "create", "mekanism", "botania", "ars_nouveau", "immersiveengineering", "embers", "pneumaticcraft", "occultism", "industrialforegoing", "quark", "pedestals", "appliedenergistics", "bloodmagic", "wizards_reborn", "eidolon", "mythicbotany", "undergarden", "biomeswevegone", "dungeons_plus", "natures_spirit"]

