ServerEvents.recipes(e => {
    e.remove({ id: /architects_palette:.*sunmetal_brick_from_sunmetal_blend/ })
    e.recipes.mbd2.ember_oven()
        .inputItems('architects_palette:sunmetal_blend')
        .inputFluids(Fluid.of('starbunclemania:source_fluid', 250))
        .perTick(t => t.inputEmber(2))
        .outputItems('architects_palette:sunmetal_brick')
        .duration(20 * 15)
        .id('kubejs:mbd2/recipe_types/ember_oven/sunmetal_brick')
        
    e.remove({ id: 'irons_spellbooks:arcane_ingot' })
    e.recipes.mbd2.ember_oven()
        .inputItems('8x irons_spellbooks:arcane_dust')
        .inputFluids(Fluid.of('starbunclemania:source_fluid', 50))
        .perTick(t => t.inputEmber(1))
        .outputItems('irons_spellbooks:arcane_ingot')
        .duration(20 * 10)
        .id('kubejs:mbd2/recipe_types/ember_oven/arcane_ingot')
})