ServerEvents.recipes(e => {
    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('undergarden:virulent_mix_source', 4000))
        .item_input('occultism:spirit_attuned_gem')
        .item_output('occultism:spirit_attuned_crystal')
        .pressure(4.8)
        .speed(0.5)
        .exothermic(false)
        .temperature({ min_temp: 1973 })
        .id('kubejs:pneumaticcraft/thermo_plant/spirit_attuned_crystal')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('pneumaticcraft:plastic', 1000))
        .item_input('kubejs:rough_machine_frame_top')
        .item_output('kubejs:coated_machine_frame_top')
        .pressure(4.5)
        .speed(0.8)
        .exothermic(false)
        .temperature({ min_temp: 1873 })
        .id('kubejs:pneumaticcraft/thermo_plant/coated_machine_frame_top')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input({ type: 'pneumaticcraft:fluid', tag: 'forge:experience', amount: 8000 })
        .item_input('bloodmagic:corrupted_dust')
        .item_output('bloodmagic:defaultcrystal', 2)
        .pressure(4.8)
        .speed(0.8)
        .exothermic(true)
        .temperature({ min_temp: 1173, max_temp: 1273 })
        .id('kubejs:pneumaticcraft/thermo_plant/defaultcrystal')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('minecraft:water', 1000))
        .item_input('kubejs:smoldering_lapis_lazuli_compound')
        .item_output('pneumaticcraft:upgrade_matrix', 4)
        .pressure(2.0)
        .speed(0.8)
        .id('kubejs:pneumaticcraft/thermo_plant/upgrade_matrix')

    e.recipes.pneumaticcraft.thermo_plant()
        .item_input(/*'atum:'*/ 'kubejs:replaceme')
        .item_output('integratedterminals:menril_glass')
        .fluid_input(Fluid.of('integrateddynamics:menril_resin', 1000))
        .pressure(4.0)
        .speed(0.5)
        .exothermic(false)
        .temperature({ min_temp: 1273 })
        .id('kubejs:pneumaticcraft/thermo_plant/menril_glass')

    e.recipes.pneumaticcraft.thermo_plant()
        .item_input(/*'atum:'*/ 'kubejs:replaceme')
        .item_output('integratedterminals:chorus_glass')
        .fluid_input(Fluid.of('integrateddynamics:liquid_chorus', 1000))
        .pressure(4.0)
        .speed(0.5)
        .exothermic(false)
        .temperature({ min_temp: 1273 })
        .id('kubejs:pneumaticcraft/thermo_plant/chorus_glass')

    e.recipes.pneumaticcraft.thermo_plant()
        .item_input('minecraft:popped_chorus_fruit')
        .fluid_output(Fluid.of('integrateddynamics:liquid_chorus', 125))
        .pressure(3.0)
        .exothermic(false)
        .id('kubejs:pneumaticcraft/thermo_plant/liquid_chorus_from_chorus_fruit')

    e.recipes.pneumaticcraft.thermo_plant()
        .item_input('integrateddynamics:proto_chorus')
        .fluid_output(Fluid.of('integrateddynamics:liquid_chorus', 125))
        .pressure(3.0)
        .exothermic(false)
        .id('kubejs:pneumaticcraft/thermo_plant/liquid_chorus_from_proto_chorus')

    e.recipes.pneumaticcraft.thermo_plant()
        .item_input('rftoolsbase:machine_base')
        .item_output('rftoolspower:power_core1')
        .fluid_input(Fluid.of('thermal:redstone', 9000))
        .pressure(2.0)
        .exothermic(false)
        .temperature({ min_temp: 1973 })
        .id('kubejs:pneumaticcraft/thermo_plant/power_core1')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('mekanism:lithium', 100))
        .item_output('mekanism:dust_lithium')
        .pressure(2.0)
        .exothermic(true)
        .temperature({ max_temp: 453 })
        .id('kubejs:pneumaticcraft/thermo_plant/lithium_dust')

    e.recipes.pneumaticcraft.thermo_plant()
        // .fluid_input(Fluid.of('resourcefulbees:honey_fluid', 250))
        .fluid_input(Fluid.of('create:honey', 250))
        .item_input('mythicbotany:kvasir_blood')
        .item_output('mythicbotany:kvasir_mead')
        .pressure(4.0)
        .exothermic(false)
        .speed(0.1)
        .temperature({ max_temp: 1973 })
        .id('kubejs:pneumaticcraft/thermo_plant/kvasir_mead')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('industrialforegoing:latex', 900))
        .item_input('forge:dusts/sulfur')
        .item_output('industrialforegoing:dryrubber')
        .pressure(3.0)
        .exothermic(false)
        .speed(1.1)
        .temperature({ min_temp: 433 })
        .id('kubejs:pneumaticcraft/thermo_plant/dryrubber')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('minecraft:water', 100))
        .item_input('minecraft:spider_eye')
        .fluid_output('tconstruct:venom', 100)
        .pressure(2.0)
        .exothermic(false)
        .speed(0.5)
        .temperature({ min_temp: 373 })
        .id('kubejs:pneumaticcraft/thermo_plant/venom_from_spider_eye')

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('minecraft:water', 200))
        .item_input('minecraft:fermented_spider_eye')
        .fluid_output('tconstruct:venom', 200)
        .pressure(2.0)
        .exothermic(false)
        .speed(0.5)
        .temperature({ min_temp: 373 })

    e.recipes.pneumaticcraft.thermo_plant()
        .fluid_input(Fluid.of('pneumaticcraft:plastic', 1000))
        .item_input('kubejs:monster_mash')
        .fluid_output('pneumaticcraft:etching_acid', 1000)
        .pressure(1.0)
        .exothermic(false)
        .speed(0.5)
        .id('kubejs:pneumaticcraft/thermo_plant/etching_acid_from_monster_mash')

    let crystal_colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'white', 'black']

    for (let color of crystal_colors) {
        e.recipes.pneumaticcraft.thermo_plant()
            .fluid_input(Fluid.of('tconstruct:molten_aluminum', 18))
            .item_input(`quark:${color}_corundum_cluster`)
            .item_output(`quark:${color}_corundum_pane`)
            .pressure(4.8)
            .exothermic(false)
            .speed(0.25)
            .temperature({ min_temp: 2200 })
            .id(`kubejs:pneumaticcraft/thermo_plant/${color}_crystal_pane`)
    }
})