ServerEvents.recipes(e => {
    replaceExactInput(e, { id: 'create:crafting/kinetics/mechanical_piston' }, '#minecraft:planks', ['minecraft:piston', 'minecraft:sticky_piston'])
    replaceExactInput(e, { id: 'occultism:crafting/goggles' }, 'minecraft:leather', 'kubejs:leather_stripe')
    replaceExactInput(e, { id: 'occultism:crafting/storage_remote_inert' }, '#forge:ingots/gold', '#forge:ingots/nebu')
    replaceExactInput(e, { id: 'glassential:glass_ghostly' }, 'minecraft:ender_pearl', Item.of('naturesaura:aura_bottle', { stored_type: 'naturesaura:nether' }))
    replaceExactInput(e, { id: 'occultism:crafting/storage_remote_inert' }, '#forge:ingots/gold', '#forge:ingots/nebu')
    replaceExactInput(e, { id: 'occultism:crafting/storage_remote_inert' }, 'minecraft:stone_button', '#forge:nuggets/silver')
    replaceExactInput(e, { id: '/wilden_summon/' }, 'minecraft:lapis_block', 'meetyourfight:velvet_fortune')
    replaceExactInput(e, { mod: 'powah' }, 'powah:capacitor_basic', 'powah:capacitor_basic_large')
    replaceExactInput(e, { id: '/pressure_chamber_glass/' }, '#forge:glass', '#thermal:glass/hardened')
    replaceExactInput(e, { id: 'botania:abstruse_platform' }, 'botania:mana_pearl', 'kubejs:replaceme')
    replaceExactInput(e, { id: 'botania:spectral_platform' }, 'botania:pixie_dust', 'kubejs:replaceme')
    replaceExactInput(e, { mod: 'littlelogistics' }, '#forge:stone', 'minecraft:gray_concrete')
    replaceExactInput(e, { mod: 'modularrouters' }, 'minecraft:ender_pearl', 'botania:corporea_spark')
})